### PR TITLE
chore(deps, lint): add lint with husky and lint-staged

### PR DESCRIPTION
**Pull request by ri7nz**

### CODE REVIEW

**Comment by tjbo** [comment]
I was trying to make a fix today for select menu, but couldn't commit.

```refmt: Cannot determine default implementation parser for filename
       '/Users/tjbo/Projects/rescript-chakra/src/Components/Chakra__Select.res'.```

```Try `refmt --help' for more information.
Error happened when running command /Users/tjbo/Projects/rescript-chakra/node_modules/rescript/darwin/refmt.exe with args [
  '/Users/tjbo/Projects/rescript-chakra/src/Components/Chakra__Select.res'
]
husky - pre-commit hook exited with code 1 (error)```


https://share.getcloudapp.com/nOuvjgBo

Maybe refmt, needs another setting or option?

**Comment by tjbo** [comment]
This fixed it for me... but it seems a lil hacky.

https://forum.rescript-lang.org/t/reformat-rescript-in-place/207/11

**Comment by tjbo** [comment]
I don't know if you've tested it but according to the repo, maybe you haven't, so it should be easy for you to reproduce on your machine.

1 - Change a .res file
2 - Try to make a commit

I think it should fail for you too, but not positive, maybe it's working for you.

**Comment by tjbo** [comment]
-format

I think adding this flag to the package.json also fixes it.

**Comment by ri7nz** [comment]
@tjbo thanks, I missing commit `rescript format` for `bsfmt`. 

Here's for PRs 

https://github.com/ri7nz/rescript-chakra/pull/20

**Pull request merged**
